// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB17r5RlSs_3TuXEEscVaofrFFnkTl0fJ4',
    appId: '1:792362468045:android:014cabbceedf7b26709f84',
    messagingSenderId: '792362468045',
    projectId: 'relieflow',
    storageBucket: 'relieflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xLk3mRwSF9zbpEAo6V3H8o06onceaNs',
    appId: '1:792362468045:ios:4604b21763f38924709f84',
    messagingSenderId: '792362468045',
    projectId: 'relieflow',
    storageBucket: 'relieflow.firebasestorage.app',
    iosBundleId: 'com.example.volunteerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kMuWQiks1gEvadrJY_ILzc_JdOLKyJ0',
    appId: '1:792362468045:web:ec624554a7284009709f84',
    messagingSenderId: '792362468045',
    projectId: 'relieflow',
    authDomain: 'relieflow.firebaseapp.com',
    storageBucket: 'relieflow.firebasestorage.app',
  );
}
